# Generated by Django 5.2.9 on 2025-12-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskymail',
            name='imap_account',
        ),
        migrations.RemoveField(
            model_name='riskymail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermailaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
        migrations.CreateModel(
            name='LungCancerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('air_pollution', models.IntegerField()),
                ('dust_allergy', models.IntegerField()),
                ('occupational_hazards', models.IntegerField()),
                ('genetic_risk', models.IntegerField()),
                ('wheezing', models.IntegerField()),
                ('fatigue', models.IntegerField()),
                ('alcohol_use', models.IntegerField()),
                ('chronic_lung_disease', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('passive_smoker', models.IntegerField()),
                ('predicted_risk', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.DeleteModel(
            name='MailAttachment',
        ),
        migrations.DeleteModel(
            name='RiskyMail',
        ),
        migrations.DeleteModel(
            name='UserMailAccount',
        ),
    ]
