# Generated by Django 5.2.9 on 2025-12-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_riskymail_imap_account_remove_riskymail_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerRiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('air_pollution', models.IntegerField()),
                ('dust_allergy', models.IntegerField()),
                ('occupational_hazards', models.IntegerField()),
                ('genetic_risk', models.IntegerField()),
                ('wheezing', models.IntegerField()),
                ('fatigue', models.IntegerField()),
                ('alcohol_use', models.IntegerField()),
                ('chronic_lung_disease', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('passive_smoker', models.IntegerField()),
                ('predicted_risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.DeleteModel(
            name='LungCancerAssessment',
        ),
    ]
