# Generated by Django 5.2.9 on 2025-12-08 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cancerriskrecord_delete_lungcancerassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancerriskrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_records', to='core.user'),
        ),
    ]
