# Generated by Django 5.2.9 on 2025-12-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cancerriskrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerriskrecord',
            name='last_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancerriskrecord',
            name='suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
