# Generated by Django 5.2.9 on 2025-12-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cancerriskrecord_last_suggestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuitPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('probability', models.FloatField()),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('educ', models.IntegerField()),
                ('alcstat1', models.IntegerField()),
                ('alcdaysyr', models.IntegerField()),
                ('cigsday', models.IntegerField()),
                ('csqtryyr', models.IntegerField()),
                ('cswantquit', models.IntegerField()),
                ('deprx', models.IntegerField()),
                ('deplevel', models.IntegerField()),
            ],
        ),
    ]
