# Generated by Django 5.2.9 on 2025-12-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quitprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='quitprediction',
            name='last_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitprediction',
            name='suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
