# Generated by Django 5.2.9 on 2025-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quitprediction_last_suggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quitprediction',
            name='advice_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitprediction',
            name='risk_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
