# Generated by Django 5.2.9 on 2025-12-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quitprediction_advice_text_quitprediction_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quitprediction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quit_predictions', to='core.user'),
        ),
        migrations.AlterField(
            model_name='cancerriskrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancer_records', to='core.user'),
        ),
    ]
