# Generated by Django 5.2.9 on 2025-12-09 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_quitprediction_user_alter_cancerriskrecord_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quitprediction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cancerriskrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cancerriskrecord',
            name='last_suggestion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cancerriskrecord',
            name='predicted_risk_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cancerriskrecord',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='quitprediction',
            name='last_suggestion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quitprediction',
            name='risk_level',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='quitprediction',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
